uploads = []
outputs = []

[[generated]]
id = "WFPjFN5A0JT2RT_pNKtzv"
uri = "file://artifacts/lelo/src/assets/project-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wGvGLhR9EpE9xJGK5txQR"
uri = "file://artifacts/lelo/src/assets/project-6.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1L-rzV_zPah0yEP7VS98N"
uri = "file://artifacts/lelo/src/assets/project-7.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6fFvPTWVFNpaUin3HWdY5"
uri = "file://artifacts/lelo/src/assets/project-8.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9AuHmN1dBflQNHYwsMVKh"
uri = "file://artifacts/lelo/src/assets/project-9.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BX0_4Yi6xUfJef53sIQVN"
uri = "file://artifacts/lelo/src/assets/project-10.png"
type = "image"
title = "generated_image"

[[generated]]
id = "l8ntxFHrYga3K2bZazLAG"
uri = "file://artifacts/lelo/public/seed/cairo-apartment.png"
type = "image"
title = "cairo luxury apartment"

[[generated]]
id = "GpEaRCOF_o7CRQnFGkGOI"
uri = "file://artifacts/lelo/public/seed/cairo-villa.png"
type = "image"
title = "cairo luxury villa"

[[generated]]
id = "PI9p_xfxccGq6WbdkrdbM"
uri = "file://artifacts/lelo/public/seed/cairo-penthouse.png"
type = "image"
title = "cairo penthouse interior"
