kind = "web"
previewPath = "/"
title = "Bashak Developments"
version = "1.0.0"
id = "artifacts/lelo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22663

[services.development]
run = "pnpm --filter @workspace/lelo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lelo", "run", "build" ]
publicDir = "artifacts/lelo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22663"
BASE_PATH = "/"
